### ISSUE TITLE
Will there be support for version 10 RDB files?

### ISSUE THREAD

**Issue by JeffreyGroves** [HDT3213/rdb#22]
When running on a more recent version of a Redis RDB file, I receive the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/rdb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/rdbtools/cli/rdb.py", line 106, in main
    parser.parse(options.dump_file[0])
  File "/usr/local/lib/python3.8/site-packages/rdbtools/parser.py", line 394, in parse
    self.parse_fd(open(filename, "rb"))
  File "/usr/local/lib/python3.8/site-packages/rdbtools/parser.py", line 399, in parse_fd
    self.verify_version(f.read(4))
  File "/usr/local/lib/python3.8/site-packages/rdbtools/parser.py", line 963, in verify_version
    raise Exception('verify_version', 'Invalid RDB version number %d' % version)
Exception: ('verify_version', 'Invalid RDB version number 10')
Expecting value: line 1 column 1 (char 0)
```

Are there plans to expand the support to version 10?

Kind regards,
Jeff Groves

**Comment by HDT3213** [comment]
This repository is developed by **Go**, so it could not produce stacktrace of Python.

We have already supported rdb version 11, you could install this tool by `go install` or `brew install` or just download the executable file from release page.
